site_name: SwiftWing 介绍 文档

site_description: SwiftWing 介绍 文档
site_author: SwiftWing 团队
site_url: https://swiftwing001.github.io/SwiftWing-Contents/

theme:
  name: readthedocs

nav:
  - 主页: index.md
  - SwiftWing系列介绍:
    - 迅翼SwiftWing仿真平台: 迅翼SwiftWing仿真平台.md
    - SwiftWing-S7-Vtol: SwiftWing-S7-Vtol.md
    - P1无人机分电板: P1无人机分电板.md
    - 迅翼MS4525DO空速计: 迅翼MS4525DO空速计.md


# # 本地编译
# mkdocs build
# # 本地预览确认
# mkdocs serve
# # 提交源码到 main 分支
# git add .
# git commit -m "更新内容"
# git push origin master
# # 部署到 GitHub Pages
# mkdocs gh-deploy